### ISSUE TITLE
Update to 1.21

### ISSUE THREAD

**Issue by LucaErr** [Enecske/MobExplosionGriefingGamerule#2]
Hey ! Can you update it to 1.21 ? :-)

**Comment by Enecske** [comment]
By Thursday or Friday, hopefully :D

**Comment by LucaErr** [comment]
Wonderful !

**Comment by Enecske** [comment]
I have updated the mod to 1.21, hope you'll enjoy it! :)

**Comment by LucaErr** [comment]
Fantastic, Thank you !
