### ISSUE TITLE
1.21.3 update

### ISSUE THREAD

**Issue by vico93** [Enecske/MobExplosionGriefingGamerule#5]
Hi!

@Enecske is an 1.21.3 update in the plans?

If not, can other modders attempt to fork/PR an update themselves?

**Comment by Enecske** [comment]
It is in plans, I'll probably be able to update it by next Sunday (nov. 3)

**Comment by vico93** [comment]
Seems like @cputnam-a11y did a PR to 1.21.3 on #6

**Comment by Enecske** [comment]
Pulled #6 and further improved gamerule logic. The mod for 1.21.3 has also been uploaded to [Modrinth](https://modrinth.com/mod/mobexplosiongriefinggamerule/version/1.4.0+1.21.3).
