### ISSUE TITLE
"Mod isn't compatible with Loader's extended semantic version format"

### ISSUE THREAD

**Issue by avilonlegends** [Enecske/MobExplosionGriefingGamerule#7]
Hi there!

When using your mod, the console shows me the following error immediately when starting the game:

`
[ForkJoinPool-1-worker-4/WARN]: Mod mob_explosion_griefing uses the version 1.1.0_1.20.x which isn't compatible with Loader's extended semantic version format (Could not parse version number component '0_1'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
`

I'm using Fabric version 1.20.1.

Could you perhaps look into this, please?
Thank you in advance!

**Comment by Enecske** [comment]
As the log shows, that message is just a warning, and it doesn't cause any errors.
Other than that, in Mob Explosion Griefing Gamerule for Minecraft 1.20.3 and above the mod's version format was changed, so the warning doesn't show up in the newer versions of the mod.
